name: Linux

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.os}}-${{matrix.build_type}}-${{matrix.lib}}-${{matrix.gpu}}
    runs-on: ubuntu-latest
    container: ${{matrix.os}}
    defaults:
      run:
        shell: bash -e -o pipefail {0}
    env:
      CCACHE_DIR: ${{github.workspace}}/ccache
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu:22.04
        build_type:
          - Release
        lib:
          - shared
        gpu:
          - no-cuda

    steps:
      - name: Setup Dependencies
        run: |
          apt update
          apt install -y software-properties-common
          add-apt-repository ppa:apt-fast/stable
          apt -y install sudo apt-fast

      - uses: actions/checkout@v3
        with:
          path: ceres-solver-dir

#      - uses: awalsh128/cache-apt-pkgs-action@latest
#        with:
#          packages: libxml2 libxml2-dev libboost-all-dev build-essential ccache libbenchmark-dev libblas-dev libeigen3-dev libgflags-dev libgoogle-glog-dev
#           liblapack-dev libmetis-dev libsuitesparse-dev ninja-build libssl-dev git cmake apt-transport-https software-properties-common wget
#          version: 1.3

      - name: install deps
        run: sudo apt install libxml2 libxml2-dev libboost-all-dev build-essential ccache libbenchmark-dev libblas-dev libeigen3-dev libgflags-dev libgoogle-glog-dev
          liblapack-dev libmetis-dev libsuitesparse-dev ninja-build libssl-dev git cmake apt-transport-https software-properties-common wget -y

      - name: Cache Ceres-solver build
        id:  cache-ceres-build
        uses: actions/cache@v3
        with:
          path: ceres-solver
          key: ceres-solver-cache
          restore-keys: ceres-solver-cache

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Setup Environment
        run: echo 'CXXFLAGS=-flto' >> $GITHUB_ENV

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Clone ceres-solver
        run: |
          git clone https://ceres-solver.googlesource.com/ceres-solver
          pwd

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Make build dir
        working-directory: ceres-solver
        run: |
          mkdir build
          mkdir install

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Configure
        working-directory: ceres-solver/build
        run: cmake -DCMAKE_INSTALL_PREFIX=../install -DEXPORT_BUILD_DIR=ON ..

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Build
        working-directory: ceres-solver/build
        run: make -j4

      - name: Install
        working-directory: ceres-solver/build
        run: |
          sudo make install

      - name: Setup Dependencies
        run: |
          apt update
          apt -y install git

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: RecoMoreDir
          submodules: recursive

      - name: Add RecoMore build
        working-directory: RecoMoreDir
        run: mkdir RecoMore-build

#      - name: Test
#        working-directory: ceres-solver/build
#        run: make test


      - name: check dirs
        run: |
          echo $CERESDIR


      - name: Build RecoMore
        working-directory: RecoMoreDir/RecoMore-build
        id: recomore
        run: |
          sudo apt-get remove cmake cmake-data -y
          sudo apt-get install cmake cmake-data -y
          hash -r
          cmake --version
          CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/__w/RecoMore/RecoMore/ceres-solver/install/lib/cmake/Ceres:/__w/RecoMore/RecoMore/ceres-solver/install/:../../ceres-solver/build
          Ceres_DIR=../../ceres-solver/build
          echo "Ceres_DIR=../../ceres-solver/build" >> $GITHUB_ENV
          printenv
          echo ""
          ls $Ceres_DIR
          echo ""
          echo $CMAKE_PREFIX_PATH
          echo ""
          ls ../../ceres-solver/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/__w/RecoMore/RecoMore/ceres-solver/install/ ..
          make -j4

      - name: Run tests
        working-directory: RecoMoreDir/RecoMore-build/Tests
        run: |
          ls ..
          ls .
          ls ../TestData
          ./Boost_Tests_run
