name: Linux

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.os}}-${{matrix.build_type}}-${{matrix.lib}}-${{matrix.gpu}}
    runs-on: ubuntu-latest
    container: ${{matrix.os}}
    defaults:
      run:
        shell: bash -e -o pipefail {0}
    env:
      CCACHE_DIR: ${{github.workspace}}/ccache
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu:22.04
        build_type:
          - Release
        lib:
          - shared
        gpu:
          - no-cuda

    steps:
      - name: Setup Dependencies
        run: |
          apt update
          apt install -y software-properties-common
          add-apt-repository ppa:apt-fast/stable
          apt -y install sudo apt-fast

      - uses: actions/checkout@v3
        with:
          path: ceres-solver-dir

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2 libxml2-dev libboost-all-dev build-essential ccache libbenchmark-dev libblas-dev libeigen3-dev libgflags-dev libgoogle-glog-dev liblapack-dev libmetis-dev libsuitesparse-dev ninja-build libssl-dev git cmake apt-transport-https software-properties-common wget
          version: 1.2

      - name: Cache Ceres-solver build
        id:  cache-ceres-build
        uses: actions/cache@v3
        with:
          path: ceres-solver
          key: ceres-solver-cache
          restore-keys: ceres-solver-cache

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Setup Environment
        run: echo 'CXXFLAGS=-flto' >> $GITHUB_ENV

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Clone ceres-solver
        run: |
          git clone https://ceres-solver.googlesource.com/ceres-solver
          pwd

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Make build dir
        working-directory: ceres-solver
        run: mkdir build

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Configure
        working-directory: ceres-solver/build
        run: cmake ..

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Build
        working-directory: ceres-solver/build
        run: make -j4

      - if: steps.cache-ceres-build.outputs.cache-hit != 'true'
        name: Install
        working-directory: ceres-solver/build
        run: make install


      - name: Set ceres dir
        run: echo "CERESDIR=$(pwd)/ceres-solver" >> $GITHUB_ENV


      - name: Setup Dependencies
        run: |
          apt update
          apt -y install git

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: RecoMoreDir
          submodules: recursive

      - name: Add RecoMore build
        working-directory: RecoMoreDir
        run: mkdir RecoMore-build


      - name: check dirs
        run: |
          echo $CERESDIR
          echo ${{ env.GITHUB_SHA_SHORT }}
          pwd
          echo ""
          ls /__w/RecoMore/RecoMore
          echo ""
          ls .
          echo ""
          ls ..
          echo ""
          echo ""
          ls -R ../..
          echo ""
          ls ../../../github
          ls ../../../home
          ls ../../../usr
          ls ceres-solver

      - name: Build RecoMore
        working-directory: RecoMoreDir/RecoMore-build
        id: recomore
        run: |
          CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:ceres-solver-dir/${{ env.GITHUB_SHA_SHORT }}
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j4

      - name: Run tests
        working-directory: RecoMoreDir/RecoMore-build/Tests
        run: |
          ls ..
          ls .
          ls ../TestData
          ./Boost_Tests_run
