name: Linux

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.os}}-${{matrix.build_type}}-${{matrix.lib}}-${{matrix.gpu}}
    runs-on: ubuntu-latest
    container: ${{matrix.os}}
    defaults:
      run:
        shell: bash -e -o pipefail {0}
    env:
      CCACHE_DIR: ${{github.workspace}}/ccache
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu:22.04
        build_type:
          - Release
        lib:
          - shared
        gpu:
          - no-cuda

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dependencies
        run: |
          apt update
          apt full-upgrade -y
          apt install -y \
            build-essential \
            ccache \
            libbenchmark-dev \
            libblas-dev \
            libeigen3-dev \
            libgflags-dev \
            libgoogle-glog-dev \
            liblapack-dev \
            libmetis-dev \
            libsuitesparse-dev \
            ninja-build \
            libssl-dev \
            git \
            cmake

      - name: Setup CUDA toolkit
        if: matrix.gpu == 'cuda'
        run: |
          apt-get install -y \
            nvidia-cuda-dev \
            nvidia-cuda-toolkit


      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ceres-solver
          key: ceres-solver-cache


      - if: steps.cache-build.outputs.cache-hit != 'true'
        name: Ceres-solver
        steps:
        - name: Setup Environment
          if: matrix.build_type == 'Release'
          run: |
            echo 'CXXFLAGS=-flto' >> $GITHUB_ENV

        - name: Clone ceres-solver
          run: git clone https://ceres-solver.googlesource.com/ceres-solver

        - name: Make build dir
          working-directory: ceres-solver
          run: mkdir build

        - name: Configure
          working-directory: ceres-solver/build
          run: cmake ..

        - name: Build
          working-directory: ceres-solver/build
          run: make -j4

        - name: Install
          working-directory: ceres-solver/build
          run: make install

      - name: Build Boost
        uses: egor-tensin/build-boost@v1.4
        with:
          version: 1.80.0
          libraries: thread serialization test
          platform: x64
          configuration: Release